--1번
SELECT STUDENT_NAME "학생 이름",
          STUDENT_ADDRESS 주소지
FROM TB_STUDENT
ORDER BY 1;

--2번
SELECT STUDENT_NAME,
          STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

--3번
SELECT STUDENT_NAME 학생이름,
          STUDENT_NO 학번,
          STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS,1,3) IN ('강원도','경기도') AND
          SUBSTR(ENTRANCE_DATE,1,2) LIKE '9%'
ORDER BY 1;

--4번
SELECT PROFESSOR_NAME,
          PROFESSOR_SSN
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = '005';

--5번
SELECT STUDENT_NO, TO_CHAR(POINT,'9.99')
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE SUBSTR(TERM_NO,1,6) = '200402' AND
          CLASS_NO = 'C3118100'
ORDER BY 2 DESC,1;

--6번
SELECT STUDENT_NO,
          STUDENT_NAME,
          DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7번
SELECT CLASS_NAME,
          DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING (DEPARTMENT_NO)
ORDER BY 2;

--8번
SELECT CLASS_NAME,
          PROFESSOR_NAME
FROM TB_CLASS_PROFESSOR
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_PROFESSOR USING (PROFESSOR_NO)
ORDER BY 2,1;

--9번
SELECT CLASS_NAME,
          PROFESSOR_NAME
FROM TB_DEPARTMENT
JOIN TB_PROFESSOR USING (DEPARTMENT_NO)
JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CATEGORY = '인문사회';


--10번
SELECT STUDENT_NO 학번,
          STUDENT_NAME "학생 이름",
          ROUND(AVG(POINT),1) "전체 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 3 DESC, 1;

--11번
SELECT DEPARTMENT_NAME 학과이름,
          STUDENT_NAME 학생이름,
          PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

SELECT DEPARTMENT_NAME 학과이름,
          STUDENT_NAME 학생이름,
          PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING (DEPARTMENT_NO)
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

--12번
SELECT STUDENT_NAME,
          TERM_NO
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE TERM_NO LIKE '2007%' AND
          CLASS_NAME = '인간관계론';
          
--13번
SELECT CLASS_NAME, 
          DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND
          PROFESSOR_NO IS NULL;
/*          
SELECT CLASS_NO
FROM TB_CLASS
WHERE DEPARTMENT_NO >= '056' AND DEPARTMENT_NO <= '063'
MINUS
SELECT CLASS_NO
FROM TB_CLASS_PROFESSOR
WHERE PROFESSOR_NO IS NOT NULL;

SELECT CLASS_NO
FROM TB_CLASS
WHERE DEPARTMENT_NO >= '056' AND DEPARTMENT_NO <= '063'
INTERSECT
SELECT CLASS_NO
<<<<<<< HEAD
FROM TB_CLASS_PROFESSOR
WHERE PROFESSOR_NO IS NOT NULL;
FROM TB_CLASS_PROFESSOR;
*/

--14번
SELECT STUDENT_NAME 학생이름,
          NVL(PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT D USING (DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = (SELECT  DEPARTMENT_NAME
                                        FROM TB_DEPARTMENT
                                         WHERE DEPARTMENT_NAME = '서반아어학과');

          
--15번
SELECT STUDENT_NO 학번,
          STUDENT_NAME 이름,
          DEPARTMENT_NAME "학과 이름",
          AVG(POINT)
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) IN (SELECT AVG(POINT)
                                FROM TB_GRADE
                                GROUP BY STUDENT_NO
                                HAVING AVG(POINT) >= 4.0);
                                      
-- 16번
SELECT CLASS_NO,
          CLASS_NAME,
          TRUNC(AVG(POINT),8)
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과' AND 
          CLASS_TYPE = '전공선택'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17번
SELECT STUDENT_NAME,
          STUDENT_ADDRESS
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                     FROM TB_STUDENT
                                     WHERE STUDENT_NAME = '최경희');

-- 18번
SELECT STUDENT_NO,
          STUDENT_NAME
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT))
                                  FROM TB_GRADE
                                  JOIN TB_STUDENT USING (STUDENT_NO)
                                  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                                  WHERE DEPARTMENT_NO = '001'
                                  GROUP BY STUDENT_NO);

--19번
SELECT DISTINCT DEPARTMENT_NAME "계열 학과명",
          ROUND(AVG(POINT),1) 전공평점
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE CATEGORY = '자연과학' AND CLASS_TYPE LIKE '전공%'
GROUP BY DEPARTMENT_NAME;




          




