--1번
SELECT (SELECT COUNT(*) FROM TB_BOOK) +
          (SELECT COUNT(*) FROM TB_BOOK_AUTHOR)+
          (SELECT COUNT(*) FROM TB_PUBLISHER)+
          (SELECT COUNT(*) FROM TB_WRITER) "총데이터건수"
FROM DUAL;

--2번
SELECT TABLE_NAME,
          COLUMN_NAME,
          DATA_TYPE,
          DATA_DEFAULT,
          NULLABLE,
          CONSTRAINT_NAME,
          CONSTRAINT_TYPE,
          R_CONSTRAINT_NAME
FROM USER_TAB_COLS
JOIN USER_CONSTRAINTS USING (TABLE_NAME);
     
--3번
SELECT BOOK_NO "책 번호",
          BOOK_NM 도서명
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

--4번
SELECT TL.WRITER_NM 작가이름,
          TL.OFFICE_TELNO "사무실 전화번호",
          TL.HOME_TELNO "집 전화번호",
          TL.MOBILE_NO "휴대폰 전화번호"
FROM (SELECT WRITER_NM
         FROM TB_WRITER
         WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%'
         ORDER BY 1) NL
JOIN TB_WRITER TL ON (TL.WRITER_NM = NL.WRITER_NM)         
WHERE ROWNUM = 1;

--5번
SELECT COUNT(*)|| '명' "작가(명)"
FROM (SELECT WRITER_NO, COUNT(*)
         FROM TB_BOOK_AUTHOR B
         WHERE COMPOSE_TYPE = '옮김'
         GROUP BY WRITER_NO);

--6번
SELECT COMPOSE_TYPE "저작 형태",
          COUNT(*) "도서 수량"
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING (BOOK_NO) 
WHERE COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING COUNT(*) > 299;  

--7번
SELECT BOOK_NM 도서이름,
          ISSUE_DATE 발행일자,
          PUBLISHER_NM "출판사 이름"
FROM 
(SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM TB_BOOK
JOIN TB_PUBLISHER USING (PUBLISHER_NM)
ORDER BY 2 DESC)
WHERE ROWNUM = 1;

--8번
SELECT WRITER_NM "작가 이름",
          CO "권 수"
FROM
(SELECT WRITER_NM, COUNT(*) CO
FROM TB_BOOK_AUTHOR
JOIN TB_BOOK USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
GROUP BY WRITER_NM
ORDER BY 2 DESC
)
WHERE ROWNUM <= 3;

--9번
UPDATE TB_WRITER A
SET REGIST_DATE = (SELECT MIN(ISSUE_DATE)  
                            FROM TB_BOOK
                            JOIN TB_BOOK_AUTHOR USING (BOOK_NO)
                            WHERE A.WRITER_NO = WRITER_NO);
COMMIT;
                
--10번             
CREATE TABLE TB_BOOK_TRANSLATOR(
    BOOK_NO VARCHAR2(10) NOT NULL,
    WRITER_NO VARCHAR2(10) NOT NULL,
    TRANS_LANG VARCHAR2(60),
    CONSTRAINT PK_BOOK_TRANSLATOR PRIMARY KEY (BOOK_NO, WRITER_NO),
    CONSTRAINT FK_BOOK_TRANSLATOR_01 FOREIGN KEY (BOOK_NO) REFERENCES TB_BOOK,
    CONSTRAINT FK_BOOK_TRANSLATOR_02 FOREIGN KEY (WRITER_NO) REFERENCES TB_WRITER
);
COMMIT;
--11번
INSERT INTO TB_BOOK_TRANSLATOR (BOOK_NO, WRITER_NO)
(
SELECT BOOK_NO, WRITER_NO
FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역')
); -- 169개 행
DELETE FROM TB_BOOK_AUTHOR
WHERE COMPOSE_TYPE IN ('옮김', '역주', '편역', '공역');

--12번
SELECT BOOK_NM "번역서 이름", 
          WRITER_NM "번역자(역자)"
FROM TB_BOOK_TRANSLATOR
JOIN  TB_BOOK USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE SUBSTR(ISSUE_DATE,1,2) = '07';
          
--13번
CREATE VIEW VW_BOOK_TRANSLATOR
AS
SELECT BOOK_NM 도서명, 
          WRITER_NM 번역자,
          ISSUE_DATE 출판일
FROM TB_BOOK_TRANSLATOR
JOIN  TB_BOOK USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE SUBSTR(ISSUE_DATE,1,2) = '07'
WITH CHECK OPTION;

--14번
INSERT INTO TB_PUBLISHER
VALUES ('춘 출판사', '02-6710-3737', DEFAULT);
COMMIT;

--15번
SELECT WRITER_NM 이름,
          COUNT(*) 숫자
FROM TB_WRITER
GROUP BY WRITER_NM
HAVING COUNT(*) > 1;

--16번
UPDATE TB_BOOK_AUTHOR
SET COMPOSE_TYPE = '지음'
WHERE COMPOSE_TYPE IS NULL;
COMMIT;

--17번
SELECT WRITER_NM 이름,
          OFFICE_TELNO "사무실 전화 번호"
FROM TB_WRITER
WHERE SUBSTR(OFFICE_TELNO,1,2) = '02'
AND OFFICE_TELNO LIKE '___________';

--18번
SELECT WRITER_NM "작가 이름"
FROM TB_WRITER
WHERE TO_CHAR(TO_DATE('06/01/01', 'RR/MM/DD'),'RRRR') - TO_CHAR(REGIST_DATE,'RRRR') > 31
ORDER BY 1;

--19번
SELECT BOOK_NM 도서명,
          PRICE 가격,
          CASE
          WHEN STOCK_QTY < 5 THEN '추가주문필요'
          ELSE '소량보유'
          END 재고상태
FROM TB_PUBLISHER
JOIN TB_BOOK USING (PUBLISHER_NM)
WHERE PUBLISHER_NM = '황금가지'
AND STOCK_QTY < 10
ORDER BY STOCK_QTY DESC, 1; 

--20번
SELECT BOOK_NM 도서명,
          (SELECT WRITER_NM
           FROM TB_BOOK
           JOIN TB_BOOK_AUTHOR USING (BOOK_NO)
           JOIN TB_WRITER USING (WRITER_NO)
           WHERE BOOK_NM = '아타트롤') 저자,
          WRITER_NM 역자
FROM TB_BOOK
JOIN TB_BOOK_TRANSLATOR USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE BOOK_NM = '아타트롤';

--21번
SELECT BOOK_NM 도서명,
          STOCK_QTY 재고수량,
          PRICE "가격(Org)",
          PRICE * 0.8 "가격(NEW)"
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
WHERE MONTHS_BETWEEN(SYSDATE,REGIST_DATE) / 12 > 30
AND STOCK_QTY >= 90
ORDER BY 2 DESC, 4 DESC, 1;