--1번
SELECT (SELECT COUNT(*) FROM TB_BOOK) +
          (SELECT COUNT(*) FROM TB_BOOK_AUTHOR)+
          (SELECT COUNT(*) FROM TB_PUBLISHER)+
          (SELECT COUNT(*) FROM TB_WRITER) "총데이터건수"
FROM DUAL;

--2번
SELECT TABLE_NAME,
          COLUMN_NAME,
          DATA_TYPE,
          DATA_DEFAULT,
          NULLABLE,
          CONSTRAINT_NAME,
          CONSTRAINT_TYPE,
          R_CONSTRAINT_NAME
FROM USER_TAB_COLS
JOIN USER_CONSTRAINTS USING (TABLE_NAME);
     
--3번
SELECT BOOK_NO "책 번호",
          BOOK_NM 도서명
FROM TB_BOOK
WHERE LENGTH(BOOK_NM) >= 25;

--4번
SELECT TL.WRITER_NM 작가이름,
          TL.OFFICE_TELNO "사무실 전화번호",
          TL.HOME_TELNO "집 전화번호",
          TL.MOBILE_NO "휴대폰 전화번호"
FROM (SELECT WRITER_NM
         FROM TB_WRITER
         WHERE MOBILE_NO LIKE '019%' AND WRITER_NM LIKE '김%'
         ORDER BY 1) NL
JOIN TB_WRITER TL ON (TL.WRITER_NM = NL.WRITER_NM)         
WHERE ROWNUM = 1;

--5번
SELECT COUNT(*)|| '명' "작가(명)"
FROM (SELECT WRITER_NO, COUNT(*)
         FROM TB_BOOK_AUTHOR B
         WHERE COMPOSE_TYPE = '옮김'
         GROUP BY WRITER_NO);

--6번
SELECT COMPOSE_TYPE "저작 형태",
          COUNT(*) "도서 수량"
FROM TB_BOOK
JOIN TB_BOOK_AUTHOR USING (BOOK_NO) 
WHERE COMPOSE_TYPE IS NOT NULL
GROUP BY COMPOSE_TYPE
HAVING COUNT(*) > 299;  

--7번
SELECT BOOK_NM 도서이름,
          ISSUE_DATE 발행일자,
          PUBLISHER_NM "출판사 이름"
FROM 
(SELECT BOOK_NM, ISSUE_DATE, PUBLISHER_NM
FROM TB_BOOK
JOIN TB_PUBLISHER USING (PUBLISHER_NM)
ORDER BY 2 DESC)
WHERE ROWNUM = 1;

--8번
SELECT WRITER_NM "작가 이름",
          CO "권 수"
FROM
(SELECT WRITER_NM, COUNT(*) CO
FROM TB_BOOK_AUTHOR
JOIN TB_BOOK USING (BOOK_NO)
JOIN TB_WRITER USING (WRITER_NO)
GROUP BY WRITER_NM
ORDER BY 2 DESC
)
WHERE ROWNUM <= 3;

--9번
UPDATE TB_WRITER A
SET REGIST_DATE = (SELECT MIN(ISSUE_DATE)  
                            FROM TB_BOOK
                            JOIN TB_BOOK_AUTHOR USING (BOOK_NO)
                            WHERE A.WRITER_NO = WRITER_NO);

COMMIT;