--1번문제
SELECT COUNT(*) 학생수
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '003' AND
          ENTRANCE_DATE LIKE '01%';

--2번문제
SELECT CATEGORY 계열,
          DEPARTMENT_NAME 학과이름,
          CAPACITY 정원
FROM TB_DEPARTMENT
WHERE (CAPACITY BETWEEN 20 AND 30) AND 
           CATEGORY = '공학'
ORDER BY 2;           

--3번문제
SELECT CATEGORY 계열,
          COUNT(*) 학과수
FROM TB_DEPARTMENT
WHERE CATEGORY LIKE '%학%'
GROUP BY CATEGORY
ORDER BY 2 DESC;

--4번
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '영어영문학과';

SELECT PROFESSOR_NAME 교수이름,
          SUBSTR(PROFESSOR_SSN,1,2) 출생년도,
          PROFESSOR_ADDRESS 주소
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '002'
ORDER BY 2;

--5번
SELECT DEPARTMENT_NO
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '국어국문학과';

SELECT DEPARTMENT_NO 학과번호,
          STUDENT_NAME 학생이름,
          DECODE(ABSENCE_YN, 'Y', '휴학', '정상') 휴학여부
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001'
ORDER BY 2;

--6번
SELECT '[' || RPAD(SUBSTR(STUDENT_SSN,1,8),14,'*')||']' "[주민번호]",
          STUDENT_NAME 학생이름
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_SSN,8,1) = '2' AND
          STUDENT_NAME LIKE '김%' AND
          SUBSTR(STUDENT_SSN,1,2) = '80';

--7번
SELECT DEPARTMENT_NAME 학과이름,
          CAPACITY 정원,
          CASE 
          WHEN CAPACITY >= 40 THEN '대강의실'
          WHEN CAPACITY >= 30 THEN '중강의실'
          WHEN CAPACITY < 30 THEN '소강의실'
          END 강의실크기
FROM TB_DEPARTMENT
WHERE CATEGORY = '예체능'
ORDER BY 2 DESC;

--8번
SELECT STUDENT_NAME 학생이름,
          TO_CHAR(ENTRANCE_DATE, 'RR"년" MM"월" DD"일"') 입학일자,
          FLOOR(MONTHS_BETWEEN (SYSDATE,ENTRANCE_DATE)/12) || '년' "입학기간(년)"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_ADDRESS,1,2) IN ('경기','인천')
          AND TO_CHAR(ENTRANCE_DATE,'RRRR') LIKE '19%'
ORDER BY 3,1;          
          
--9번
SELECT DEPARTMENT_NO 학과번호,
          MIN((TO_NUMBER(TO_CHAR(SYSDATE,'RRRR')) - TO_NUMBER('19'||SUBSTR(PROFESSOR_SSN,1,2)))) "나이" 
FROM TB_PROFESSOR
WHERE PROFESSOR_ADDRESS LIKE '서울%'
GROUP BY DEPARTMENT_NO
ORDER BY 2;

--10번
SELECT DEPARTMENT_NO 학과번호,
          STUDENT_NAME 학생이름,
          COACH_PROFESSOR_NO 지도교수번호,
          TO_CHAR(ENTRANCE_DATE, 'RRRR"년"') 입학년도
FROM TB_STUDENT
WHERE ENTRANCE_DATE BETWEEN '05/01/01' AND '06/12/31'
          AND STUDENT_ADDRESS IS NULL AND
          SUBSTR(STUDENT_SSN,8,1) = 1
ORDER BY 4;


