--11번
SELECT SUBSTR(TERM_NO,1,4) 년도,
          ROUND(AVG(POINT),1) 평점
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE COACH_PROFESSOR_NO IN (SELECT COACH_PROFESSOR_NO
                                             FROM TB_STUDENT
                                             WHERE STUDENT_NAME = '서가람')
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1 DESC;

--12번
SELECT DEPARTMENT_NAME 학과명,
          STUDENT_NAME 학생명,
          ENTRANCE_DATE 입학일자
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE STUDENT_SSN LIKE '_______1%' AND
          ABSENCE_YN = 'Y' AND
          ENTRANCE_DATE BETWEEN '01/01/01' AND SYSDATE
ORDER BY 3 DESC;          
          
--13번
SELECT PROFESSOR_NAME 지도교수,
          COUNT(*) 학생수
FROM TB_STUDENT
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING (PROFESSOR_NO)
WHERE CLASS_NO IS NULL
GROUP BY PROFESSOR_NAME;

--14번
SELECT STUDENT_NAME 학생이름,
          TERM_NO 학기,
          ROUND(AVG(POINT),1) 학점
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CATEGORY = '공학' AND
           TERM_NO LIKE '2009%'
GROUP BY STUDENT_NAME, TERM_NO
HAVING ROUND(AVG(POINT),1) >= 4.0
ORDER BY 3 DESC,1;

--15번
SELECT SUBSTR(TERM_NO,1,4) 년도,
          SUBSTR(TERM_NO,5,2) 학기,
          ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
JOIN TB_STUDENT USING (STUDENT_NO)
WHERE SUBSTR(TERM_NO,1,4) IN ('2007','2008') AND
          DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                     FROM TB_STUDENT
                                     WHERE STUDENT_NAME = '김고운')
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));

--16번
SELECT SUBSTR(TERM_NO,1,4) 년도,
          SUBSTR(TERM_NO,5,2) 학기,
          TO_CHAR(ROUND(AVG(POINT),1),'9.9') 평점
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
WHERE SUBSTR(TERM_NO,1,4) = '2004' AND
          DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                                    FROM TB_CLASS
                                    WHERE CLASS_NAME = '문학과생태학')
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2));                                     

--17번
SELECT STUDENT_NAME 학생이름,
          PROFESSOR_NAME 지도교수
FROM TB_STUDENT
JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO LIKE 'A__3___' AND
          COACH_PROFESSOR_NO IN (SELECT PROFESSOR_NO
                                                 FROM TB_PROFESSOR
                                                 WHERE PROFESSOR_NAME LIKE '이%')
ORDER BY 1;
--18번          
SELECT CATEGORY 계열,
          DEPARTMENT_NAME 학과이름,
          COUNT(*) 학생수
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING ( DEPARTMENT_NO)
WHERE DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
                                        FROM TB_STUDENT
                                        JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
                                        WHERE CATEGORY IN ('예체능','의학'))
GROUP BY CATEGORY, DEPARTMENT_NAME
ORDER BY 1,3 DESC;

--19번
SELECT CLASS_NAME 과목,
          (SELECT PREATTENDING_CLASS_NO
          FROM TB_CLASS 
          WHERE PREATTENDING_CLASS_NO IS NOT NULL)
FROM TB_CLASS
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '행정학과' AND
            PREATTENDING_CLASS_NO IS NOT NULL;
          
SELECT CLASS_NAME 과목,
          (SELECT CLASS_NAME
          FROM TB_CLASS 
          WHERE C.CLASS_NO = CLASS_NO)
FROM TB_CLASS C
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '행정학과' AND
PREATTENDING_CLASS_NO IS NOT NULL;
           
            
            